# Generated by Django 3.0.4 on 2022-05-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_sys',
        ),
        migrations.RemoveField(
            model_name='department',
            name='short_notation',
        ),
    ]
