# Generated by Django 3.0.4 on 2022-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeservice', '0008_auto_20220526_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocuments',
            name='file_path',
            field=models.FileField(null=True, upload_to='Employee_doc/'),
        ),
    ]
