# Generated by Django 3.0.4 on 2022-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeservice', '0009_auto_20220527_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departement',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employeepersionalinfo',
            name='nationality',
            field=models.SmallIntegerField(max_length=128, null=True),
        ),
    ]
