# Generated by Django 3.0.4 on 2022-05-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeservice', '0010_auto_20220528_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersionalinfo',
            name='nationality',
            field=models.SmallIntegerField(default=1),
        ),
    ]
